trigger:
- master
 
pool:
  name: Azure Pipelines
  vmImage: 'ubuntu-latest'
 
variables:
  env: 'prod'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
 
steps:
- task: GoTool@0
  displayName: 'Use Go 1.13'

- task: Go@0
  displayName: 'go get'
  inputs:
    arguments: '-d'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      echo "pwd"
      pwd
      echo "ls -al"
      ls -al
      echo "find"
      find cmd
- task: Go@0
  displayName: 'go build'
  inputs:
    command: build
    arguments: '-o semverutil cmd/version/main.go'

- task: ArchiveFiles@2
  displayName: 'Archive files'
  inputs:
    rootFolderOrFile: '$(Build.Repository.LocalPath)'
    includeRootFolder: False

- task: PublishBuildArtifacts@1
  displayName: 'Publish artifact'
  condition: succeededOrFailed()
