trigger:
- master
 
pool:
  name: Azure Pipelines
  vmImage: 'ubuntu-latest'
 
variables:
  env: 'prod'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
 
steps:
- task: GoTool@0
  displayName: 'Use Go 1.13'

- task: Go@0
  displayName: 'go get'
  inputs:
    arguments: '-d'

- task: Go@0
  displayName: 'go build'
  inputs:
    command: build
    arguments: '-o "$(System.TeamProject)/semverutil" cmd/version/*'

- task: ArchiveFiles@2
  displayName: 'Archive files'
  inputs:
    rootFolderOrFile: '$(Build.Repository.LocalPath)'
    includeRootFolder: False

- task: PublishBuildArtifacts@1
  displayName: 'Publish artifact'
  condition: succeededOrFailed()
