trigger: none

  # minor change
  # branches:
  #   include:
  #   - develop
  # paths:
  #   exclude:
  #   - RELEASES.txt
  #   - azure_pipelines-develop.yml
  #   - azure_pipelines.yml
 
pool:
  name: Azure Pipelines
  vmImage: 'ubuntu-latest'
 
variables:
  env: 'prod'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

stages:
- stage: stage_1
  displayName: 'build and test'
  jobs:
  - job: Provision
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: GoTool@0
      displayName: 'Use Go 1.13'
      inputs:
        version: 1.13
    - task: Go@0
      displayName: 'go get'
      inputs:
        arguments: '-d'
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          go get -v github.com/marshyon/semverUtils
          go get -v github.com/cucumber/godog/cmd/godog
          go get -v github.com/jstemmer/go-junit-report
      displayName: 'initialise project'
    - task: Go@0
      inputs:
        command: 'test'
        arguments: '-v ./...'
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          /home/vsts/go/bin/godog
          /home/vsts/go/bin/godog --format=junit > godog_test_results.xml
          go test -v ./... | /home/vsts/go/bin/go-junit-report > go_test_report.xml
      displayName: 'run godog tests'
    - task: PublishTestResults@2
      inputs:
        testResultsFormat: 'JUnit'
        testResultsFiles: |
          godog_test_results.xml
          go_test_report.xml
        mergeTestResults: true      
    - task: Go@0
      displayName: 'go build'
      inputs:
        command: build
        arguments: '-o semverutil cmd/version/main.go'
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          ./semverutil
      displayName: 'run semverutil'
